<template>
    <layout-default>

        <h1>New project!</h1>

        <p>
            You received a new contact request via the BrainShift platform.
            Details of the project are displayed below.
        </p>

        <p>Project location</p>
        <p>location 1</p>
        <p>location 2</p>
        <p>location 3</p>

        <p>Situation</p>

        <p>Size</p>

        <p>Type of farm</p>

        <p>Configuration</p>

        <p>Project Goal</p>

        <p>Contact</p>

        <p>
            Please contact the farmer within 5 business days
        </p>
        <a
            :href="'/my-account/requests/project/' + project.id + '/request/' + request.id + '/view'"
            class="button button--fill button--span"
        >
            More information
        </a>

        <p>
            In the attachment you can find the documents generated by the farmer
            to configue the building
        </p>


    </layout-default>
</template>

<script>
    
import { Link } from '@inertiajs/inertia-vue3'
import LayoutDefault from '../../Layout/Base.vue'

export default {
    components: {
        LayoutDefault,
        Link,
    },
    props: {
        project: Array,
        request: Array,
    },
};
</script>
